#!/bin/sh
#
# Copyright (C) 2011 Denis Roio <jaromil@nimk.nl>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# wait the boot to complete

APPROOT=/apps/ploop

if [ "$1" = "stop" ]; then
    UPNPPORT="`lsof -a -i4 -sTCP:LISTEN -c DMARender -F n | awk -v FS=':' '/^n/ {print $2}'`"
    $APPROOT/bin/avremote -p $UPNPPORT stop
    umount /apps/ploop
    exit 0
fi

# wait until boot is completed
sleep 15

touch /tmp/ploop.log
# USBROOT=`mount | awk '/.tmp.mnt/ { print $3}'`
USBROOT=`cat /tmp/appsRoot | grep ploop | sed 's/ploop//`
echo "PLoop app running on USB $USBROOT" >> /tmp/ploop.log
date >> /tmp/ploop.log
echo "args: $@" >> /tmp/ploop.log

# if there is a custom osd, we have to wait longer
ls $USBROOT/ | grep 'osd.bin$'
if [ $? = 0 ]; then
    sleep 15
fi

# find out the UPNP port listening on localhost
UPNPPORT="`lsof -a -i4 -sTCP:LISTEN -c DMARender -F n | awk -v FS=':' '/^n/ {print $2}'`"

export USBROOT
export APPROOT
export UPNPPORT

# wait that the usb is mounted
sleep 10

# kill dmaosd!
killall dmaosd

# will get ready for play
file=`ls $USBROOT/video`
$APPROOT/bin/avremote -s 127.0.0.1 -p $UPNPPORT load "$USBROOT/video/$file" \
    >> /tmp/ploop.log

$APPROOT/bin/avremote -s 127.0.0.1 -p $UPNPPORT mode REPEAT_ONE \
    >> /tmp/ploop.log

$APPROOT/bin/avremote -s 127.0.0.1 -p $UPNPPORT play >> /tmp/ploop.log

# done! this will loop one file indefinitely

# if you need to customize stuff (playlist etc.) you can edit this
# source and refer to avremote documentation on
# http://nimk.nl/avremote or ask for help on the WDLXTV forum on
# http://forum.wdlxtv.com

